### ISSUE TITLE
Wrong method to work with CoreData private context

### ISSUE THREAD

**Issue by eugeniobaglieri** [StorageKit/StorageKit#11]
In CoreDataStorage.swift file this function is not well implemented:

```swift
func performBackgroundTask(_ taskClosure: @escaping TaskClosure) {
        let context = makePrivateContext()

        backgroundTaskQueue.async { [unowned self] in
            taskClosure(context, self.backgroundTaskQueue)
        }
    }
```

Instead of a background queue you should use the NSManagedOBjectContest performBlock() method

**Comment by MarcoSantarossa** [comment]
Hey @eugeniobaglieri , thank you for pointing it out. I'll change asap.

**Comment by MarcoSantarossa** [comment]
Fixed with https://github.com/StorageKit/StorageKit/pull/12. Thank you for the contribution.
