### ISSUE TITLE
'SortDescriptor' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by MarcoSantarossa** [StorageKit/StorageKit#6]
## What did you do?

Imported `RealmSwift` to use `Object` class and then used also `SortDescriptor`, everything in the same file.

ℹ Please add here the steps to reproduce the issue.  

### Platform

- [x] iOS
- [x] macOS
- [x] tvOS

### StorageKit Version

0.1.1

## What did you expect to happen

We shouldn't have any compile errors.

## What happened instead?

The compile error `'SortDescriptor' is ambiguous for type lookup in this context`

## Demo Project

[Gist](https://gist.github.com/MarcoSantarossa/4a8ef480bf362a5d6be112473a55c08a)

**Comment by MarcoSantarossa** [comment]
We can fix this compile error changing the import:

```
import class RealmSwift.Object
```

The problem is that `RealmSwift` has already an object called `SortDescriptor` which makes a conflict with the one of `StorageKit`.

For the moment, we can avoid changing the library since we would rarely have this scenario.

**Comment by ennioma** [comment]
Wouldn't it be better to change anything exposed by StorageKit (especially enums and utils) adding the prefix SK?

**Comment by ghost** [comment]
where to put import class RealmSwift.Object? I'm having issue with Xcode 13 now (currently at RealmSwift (10.15.1))

**Comment by OlgaSolovjova** [comment]
If you use `SortDescriptor` just add 

```
import RealmSwift

typealias SortDescriptor = RealmSwift.SortDescriptor
```
