### ISSUE TITLE
Model vs Entity

### ISSUE THREAD

**Issue by zdnk** [StorageKit/StorageKit#7]
Hey,

I was looking at the examples and it seems like you still have to have 2 fetching codes based on which storage type is it using. The difference is only if is CoreData managed object or Realm object. I think this could also be abstracted out in the way that objects returned from the storage would actually be some structs that the entities would map to. We are using this approach currently at our project.

**Comment by MarcoSantarossa** [comment]
Hi @zdenektopic, thank you very much for your suggestion. Would you mind linking a Gist with your idea? In this way we are sure to understand it .

Thank you ☺️

**Comment by lottadot** [comment]
@zdenektopic So you're proposing after every NSFetchRequest of Foo Entities, they'd all be converted over to Struct representations?

If you had a lot of data, wouldn't this create a lot of overhead? 
How would you envision it working with something like NSFetchedResultsController?

(Obviously my questions and references are for CoreData, and leave out a similar question when using Realm).

**Comment by zdnk** [comment]
Yes, that is my proposal, it will make the code independent of the backing storage solution - Realm or CoreData.

Regarding the overhead. Well, the structs are pretty simple and performant and it also allows the developer to go immutable with properties that should not change. It has more benefits I believe. The one overhead that is most expensive regarding this, is allocation of memory for those Entities or ManagedObjects, it would depend on the solution - either keep them alive in memory which might be difficult to determine when to release them or simpler solution - allocate/fetch them whenever you need to work with those - meaning updating the records (and possibly deleting if required)

NSFetchedResultsController is something I have never used. However, you would have to introduce your own FetchedResultsController solution that could also work with any backing storage.

**Comment by MarcoSantarossa** [comment]
I agree that this approach would allow us to introduce a level of abstraction for the entity. My main concern is that it would introduce an additional level of complexity in the public interface of StorageKit. Our goal is keeping the interface as plain as possible.

**Comment by zdnk** [comment]
I don't think the public interface would be more complex, probably just the structs would have to implements some sort of protocol.
I can understand why you want to keep the interface plain, but it is also meant to provide abstraction over database/ORM solutions, which it currently does to some extensions, but you still have to write platform specific code.

**Comment by ennioma** [comment]
This could be discussed again after a couple of releases already planned. 👍🏼
